import { Platform, StyleSheet } from 'react-native';
import { colors as C } from './data';

const display = Platform.select({
  web: 'Impact, Haettenschweiler, "Arial Black", sans-serif',
  ios: 'Arial Rounded MT Bold',
  android: 'sans-serif-condensed',
}) as string;
const body = Platform.select({
  web: '"Trebuchet MS", Arial, sans-serif',
  ios: 'Avenir Next',
  android: 'sans-serif-medium',
}) as string;

export const styles = StyleSheet.create({
  outer: { flex: 1, backgroundColor: '#08010f', alignItems: 'center' },
  phone: { flex: 1, width: '100%', maxWidth: 480, overflow: 'hidden' },
  phoneDesktop: { marginVertical: 14, borderRadius: 30, borderWidth: 5, borderColor: '#4b1763', ...Platform.select({ web: { boxShadow: '0 24px 70px rgba(0,0,0,.72)' as any }, default: {} }) },
  background: { flex: 1 }, safe: { flex: 1 }, fill: { flex: 1 },
  page: { flex: 1, alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 19, paddingTop: 18, paddingBottom: 18 },
  pageScroll: { minHeight: '100%', alignItems: 'center', paddingHorizontal: 19, paddingTop: 18, paddingBottom: 22 },

  ray: { position: 'absolute', left: '49%', top: '48%', width: 880, height: 34, backgroundColor: 'rgba(173,56,208,.14)', ...Platform.select({ web: { transformOrigin: 'left center' as any }, default: {} }) },
  centerGlowOuter: { position: 'absolute', width: 430, height: 430, borderRadius: 215, left: '5%', top: '27%', backgroundColor: 'rgba(212,30,144,.07)' },
  centerGlow: { position: 'absolute', width: 255, height: 255, borderRadius: 128, left: '23%', top: '36%', backgroundColor: 'rgba(250,66,200,.10)', shadowColor: '#f330d0', shadowOpacity: .42, shadowRadius: 38 },
  confetti: { position: 'absolute', width: 8, height: 19, borderRadius: 6, opacity: .98 },
  cloudA: { position: 'absolute', width: 260, height: 122, borderRadius: 130, bottom: -70, left: -105, backgroundColor: '#25063b' },
  cloudB: { position: 'absolute', width: 290, height: 145, borderRadius: 145, bottom: -92, left: 58, backgroundColor: '#1d042f' },
  cloudC: { position: 'absolute', width: 260, height: 130, borderRadius: 130, bottom: -72, right: -105, backgroundColor: '#31084b' },
  cloudD: { position: 'absolute', width: 150, height: 78, borderRadius: 80, bottom: -30, right: 68, backgroundColor: '#27063e' },

  outlinedWrap: { alignSelf: 'center', position: 'relative' },
  displayText: { fontFamily: display, color: C.cream, textAlign: 'center', letterSpacing: 1.4 },
  outlineCopy: { position: 'absolute', color: '#1a0628' },
  header: { alignItems: 'center', marginTop: 10, zIndex: 2 },
  headerCompact: { marginTop: 4 },
  headerFirst: { fontSize: 34, lineHeight: 35 },
  headerSecond: { fontSize: 48, lineHeight: 48, marginTop: -5 },
  headerFirstCompact: { fontSize: 28, lineHeight: 29 },
  headerSecondCompact: { fontSize: 42, lineHeight: 43 },
  headerSpark: { width: 38, height: 5, borderRadius: 4, backgroundColor: C.pink, marginTop: 7, transform: [{ rotate: '-5deg' }] },

  buttonShell: { width: '100%', borderRadius: 20, borderWidth: 4, borderColor: '#35103f', padding: 3, backgroundColor: '#ff6b13', shadowColor: '#ff5b20', shadowOpacity: .8, shadowRadius: 13, shadowOffset: { width: 0, height: 0 } },
  buttonShellPurple: { backgroundColor: '#d936db', shadowColor: '#ee38fa', borderColor: '#321041' },
  buttonShellSmall: { marginTop: 8 },
  button: { minHeight: 62, borderRadius: 13, borderWidth: 2, borderColor: '#ffd45b', alignItems: 'center', justifyContent: 'center', overflow: 'hidden' },
  buttonPurple: { borderColor: '#db75f0' },
  buttonShine: { position: 'absolute', left: 10, right: 10, top: 4, height: 2, borderRadius: 4, backgroundColor: 'rgba(255,255,255,.36)' },
  buttonText: { fontFamily: display, color: '#25102f', fontSize: 25, letterSpacing: 1.2, textAlign: 'center' },
  buttonTextLight: { color: C.cream, textShadowColor: '#2a0a37', textShadowOffset: { width: 2, height: 2 }, textShadowRadius: 0 },
  pressed: { transform: [{ scale: .985 }, { translateY: 2 }], opacity: .94 },

  back: { position: 'absolute', left: 12, top: 11, zIndex: 20, width: 47, height: 47, borderRadius: 14, backgroundColor: '#32104b', borderWidth: 3, borderColor: '#9a47b8', alignItems: 'center', justifyContent: 'center', shadowColor: '#c342dc', shadowOpacity: .5, shadowRadius: 8 },
  backText: { fontFamily: display, color: C.cream, fontSize: 41, lineHeight: 42, marginTop: -5 },
  topIcon: { position: 'absolute', top: 13, zIndex: 5, width: 45, height: 45, borderRadius: 23, backgroundColor: '#33104b', borderWidth: 3, borderColor: '#8f3cac', alignItems: 'center', justifyContent: 'center', shadowColor: '#c942dd', shadowOpacity: .45, shadowRadius: 7 },
  topIconText: { fontSize: 21, color: C.yellow, fontFamily: display },

  homeHero: { flex: 1, width: '100%', alignItems: 'center', justifyContent: 'center', paddingTop: 12 },
  homeWordWrap: { zIndex: 4, transform: [{ rotate: '-3deg' }], marginBottom: -13 },
  homeWord: { fontSize: 68, lineHeight: 60, letterSpacing: 2.4 },
  homeMonsterGlow: { position: 'absolute', width: 274, height: 274, borderRadius: 137, bottom: 4, backgroundColor: 'rgba(208,49,185,.15)', shadowColor: '#f149d5', shadowOpacity: .38, shadowRadius: 32 },
  homeMonster: { zIndex: 2 },
  homeBottom: { width: '100%', gap: 13 },
  playersPill: { alignSelf: 'center', flexDirection: 'row', alignItems: 'center', gap: 9, backgroundColor: 'rgba(29,4,45,.78)', paddingHorizontal: 22, paddingVertical: 9, borderRadius: 22 },
  playersIcon: { color: C.cyan, fontFamily: display, fontSize: 10, letterSpacing: -2 },
  playerCount: { color: C.orange, fontFamily: display, fontSize: 16, letterSpacing: 1.4 },

  modeList: { width: '100%', gap: 11 },
  modeOuter: { width: '100%', padding: 3, borderRadius: 21, backgroundColor: '#8b329d', borderWidth: 3, borderColor: '#25062f', shadowColor: '#bd39cc', shadowOpacity: .32, shadowRadius: 7 },
  modeSelected: { backgroundColor: C.orange, borderColor: '#ffb321', shadowColor: C.orange, shadowOpacity: .92, shadowRadius: 14 },
  modeCard: { height: 130, borderRadius: 15, flexDirection: 'row', alignItems: 'center', paddingLeft: 12, overflow: 'hidden' },
  modePattern: { position: 'absolute', width: 260, height: 260, borderRadius: 130, right: -110, top: -80, borderWidth: 24, borderColor: 'rgba(255,255,255,.08)' },
  modeIconBadge: { width: 58, height: 58, borderRadius: 29, backgroundColor: 'rgba(32,7,43,.40)', borderWidth: 2, borderColor: 'rgba(255,255,255,.23)', alignItems: 'center', justifyContent: 'center' },
  modeClock: { color: '#ff69c6', fontFamily: display, fontSize: 38, textAlign: 'center' },
  modeText: { flex: 1, paddingLeft: 14 },
  modeTitle: { color: C.cream, fontFamily: display, fontSize: 28, lineHeight: 25, letterSpacing: .8, textShadowColor: '#311038', textShadowOffset: { width: 2, height: 3 }, textShadowRadius: 0 },
  modeTime: { color: '#ff83d1', fontFamily: display, fontSize: 15, marginTop: 7, letterSpacing: 1.1 },
  selectedTick: { position: 'absolute', right: 6, top: 6, width: 25, height: 25, borderRadius: 13, backgroundColor: C.yellow, borderWidth: 2, borderColor: C.cream, alignItems: 'center', justifyContent: 'center' },
  selectedTickText: { color: '#35102e', fontFamily: display, fontSize: 15 },

  joinCharacters: { height: 138, width: 250, flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'center', marginBottom: -25 },
  joinMonsterLeft: { transform: [{ rotate: '-8deg' }, { translateX: 12 }] },
  joinMonsterRight: { transform: [{ rotate: '8deg' }, { translateX: -12 }] },
  codePanel: { width: '100%', backgroundColor: 'rgba(31,4,48,.95)', borderRadius: 23, borderWidth: 4, borderColor: '#a92dc4', paddingHorizontal: 12, paddingVertical: 25, alignItems: 'center', shadowColor: '#ef30ed', shadowOpacity: .72, shadowRadius: 17 },
  panelLabel: { color: C.cream, fontFamily: display, fontSize: 18, marginBottom: 18, letterSpacing: 1.3 },
  codeRow: { flexDirection: 'row', gap: 7 },
  codeBox: { width: 57, height: 76, borderRadius: 14, backgroundColor: '#32104b', borderWidth: 3, borderColor: '#d446e6', alignItems: 'center', justifyContent: 'center', shadowColor: '#f33ce8', shadowOpacity: .8, shadowRadius: 9 },
  codeLetter: { color: C.cream, fontFamily: display, fontSize: 37, textShadowColor: '#13021d', textShadowOffset: { width: 2, height: 3 }, textShadowRadius: 0 },
  hiddenCodeInput: { position: 'absolute', opacity: .01, width: '94%', height: '100%' },
  pasteCode: { color: '#ff61d0', fontFamily: display, fontSize: 12, letterSpacing: .8, marginTop: 20 },
  joinHint: { color: '#c995da', fontFamily: body, fontSize: 13, textAlign: 'center' },

  nameBlock: { width: '100%', alignItems: 'center', gap: 7 },
  nameLabel: { color: '#e09bea', fontFamily: display, fontSize: 13, letterSpacing: 1.4 },
  namePanel: { width: '100%', height: 49, borderRadius: 14, borderWidth: 3, borderColor: '#9632b1', backgroundColor: '#230436', alignItems: 'center', justifyContent: 'center', shadowColor: '#b936ce', shadowOpacity: .3, shadowRadius: 7 },
  nameValue: { color: C.cream, fontFamily: display, fontSize: 22, letterSpacing: 1.4 },
  characterGrid: { width: '100%', flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', rowGap: 9 },
  characterTile: { width: '23.4%', height: 116, borderRadius: 15, backgroundColor: '#300747', borderWidth: 3, borderColor: '#662080', alignItems: 'center', justifyContent: 'center', overflow: 'hidden' },
  characterTileSelected: { borderColor: '#ff8a19', borderWidth: 4, backgroundColor: '#59201c', shadowColor: '#ff7119', shadowOpacity: .88, shadowRadius: 9 },
  checkBadge: { position: 'absolute', top: 3, left: 3, zIndex: 3, width: 25, height: 25, borderRadius: 8, backgroundColor: C.orange, borderWidth: 2, borderColor: C.cream, alignItems: 'center', justifyContent: 'center' },
  checkText: { color: C.cream, fontFamily: display, fontSize: 15 },
  characterName: { color: C.cream, fontFamily: display, fontSize: 11, letterSpacing: .5, marginTop: -2 },
  characterPicker: { width: '100%', height: 53, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: '#25053a', borderWidth: 3, borderColor: '#6f2389', borderRadius: 15, paddingHorizontal: 6 },
  pickerArrow: { color: C.cream, backgroundColor: '#51166c', fontFamily: display, fontSize: 35, width: 41, height: 39, lineHeight: 34, textAlign: 'center', borderRadius: 10 },
  pickerCenter: { alignItems: 'center' },
  pickerLabel: { color: '#b97bcd', fontFamily: display, fontSize: 8, letterSpacing: 1.3 },
  pickerName: { color: C.cream, fontFamily: display, fontSize: 21, lineHeight: 24, letterSpacing: 1.3 },

  lobbyCode: { width: '100%', height: 82, borderRadius: 17, borderWidth: 3, borderColor: '#e536ee', backgroundColor: '#230436', alignItems: 'center', justifyContent: 'center', shadowColor: '#f02af0', shadowOpacity: .76, shadowRadius: 14 },
  lobbyCodeLine: { flexDirection: 'row', alignItems: 'center', gap: 16 },
  lobbyCodeText: { color: C.cream, fontFamily: display, fontSize: 31, letterSpacing: 9 },
  copyIcon: { color: '#f6d9ff', fontFamily: display, fontSize: 19 },
  readyPill: { backgroundColor: '#3b0b51', borderRadius: 16, borderWidth: 2, borderColor: '#6c2084', paddingHorizontal: 17, paddingVertical: 5 },
  readyCount: { color: '#ff64ce', fontFamily: display, fontSize: 14, letterSpacing: .8 },
  lobbyRows: { width: '100%', gap: 7 },
  lobbyRow: { height: 58, borderRadius: 14, borderWidth: 2, borderColor: '#70228b', backgroundColor: 'rgba(34,4,52,.96)', flexDirection: 'row', alignItems: 'center', paddingHorizontal: 9 },
  lobbyAvatar: { width: 54, height: 51, borderRadius: 11, backgroundColor: '#3a0c51', alignItems: 'center', justifyContent: 'center', overflow: 'hidden' },
  lobbyName: { color: C.cream, fontFamily: display, fontSize: 17, letterSpacing: .5, flex: 1, marginLeft: 9 },
  readyDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: C.green, marginRight: 6, shadowColor: C.green, shadowOpacity: 1, shadowRadius: 5 },
  readyText: { color: C.green, fontFamily: display, fontSize: 11, letterSpacing: .6 },
  playerHero: { width: '100%', alignItems: 'center' },
  playerHeroGlow: { position: 'absolute', width: 220, height: 220, borderRadius: 110, top: 20, backgroundColor: 'rgba(231,55,214,.12)', shadowColor: '#ed45de', shadowOpacity: .5, shadowRadius: 25 },
  selectedNamePlate: { width: '78%', height: 45, marginTop: -7, backgroundColor: '#35104c', borderRadius: 15, borderWidth: 3, borderColor: '#9a34b4', alignItems: 'center', justifyContent: 'center' },
  selectedNameText: { color: C.cream, fontFamily: display, fontSize: 22, letterSpacing: 1.2 },
  waitPanel: { width: '100%', borderRadius: 20, borderWidth: 3, borderColor: '#8d2ca6', backgroundColor: '#230537', padding: 15, alignItems: 'center', shadowColor: '#b02dc8', shadowOpacity: .4, shadowRadius: 10 },
  waitTitle: { color: '#ff59ca', fontFamily: display, fontSize: 18, marginBottom: 12, letterSpacing: .8 },
  waitCode: { color: C.cream, fontFamily: display, fontSize: 28, letterSpacing: 7, marginVertical: 5 },
  miniLine: { flexDirection: 'row', justifyContent: 'center', marginTop: 7 },
  sixPlayers: { color: '#ff65cf', fontFamily: display, fontSize: 14, marginTop: 5, letterSpacing: .8 },

  spinnerHint: { color: '#ff7ad4', fontFamily: display, fontSize: 13, letterSpacing: 1.8, marginTop: -5 },
  carousel: { width: 700, height: 436, flexDirection: 'row', alignItems: 'center', justifyContent: 'center' },
  carouselGlow: { position: 'absolute', width: 290, height: 290, borderRadius: 145, backgroundColor: 'rgba(247,54,207,.16)', shadowColor: '#f035da', shadowOpacity: .7, shadowRadius: 40 },
  centerPosterSlot: { zIndex: 4, alignItems: 'center' },
  leftPoster: { position: 'absolute', left: 26, opacity: .64, transform: [{ rotate: '-11deg' }, { scale: .95 }] },
  rightPoster: { position: 'absolute', right: 26, opacity: .64, transform: [{ rotate: '11deg' }, { scale: .95 }] },
  posterFrame: { borderRadius: 16, borderWidth: 5, borderColor: '#1d0528', overflow: 'hidden', backgroundColor: '#1d0528', shadowColor: '#f342d8', shadowOpacity: .88, shadowRadius: 14 },
  posterCenter: { width: 250, height: 362 },
  posterSide: { width: 174, height: 274 },
  poster: { flex: 1, alignItems: 'center', paddingTop: 10, overflow: 'hidden' },
  posterBurstA: { position: 'absolute', width: 320, height: 42, left: 90, top: 155, backgroundColor: 'rgba(255,217,47,.12)', transform: [{ rotate: '38deg' }] },
  posterBurstB: { position: 'absolute', width: 320, height: 42, right: 90, top: 165, backgroundColor: 'rgba(255,217,47,.12)', transform: [{ rotate: '-38deg' }] },
  posterBurstC: { position: 'absolute', width: 80, height: 300, top: 65, backgroundColor: 'rgba(255,255,255,.06)', transform: [{ rotate: '17deg' }] },
  posterTopBar: { backgroundColor: 'rgba(34,5,43,.32)', borderRadius: 8, paddingHorizontal: 9, paddingVertical: 3 },
  posterTop: { color: C.cream, fontFamily: display, fontSize: 8, letterSpacing: 1.5 },
  posterTitle: { fontSize: 34, lineHeight: 30, letterSpacing: 1.1, marginTop: 10 },
  posterTitleSide: { fontSize: 24, lineHeight: 22, marginTop: 8 },
  posterSticker: { width: 64, height: 64, borderRadius: 32, backgroundColor: '#fff1b7', borderWidth: 4, borderColor: '#35103b', alignItems: 'center', justifyContent: 'center', marginTop: 5, transform: [{ rotate: '-7deg' }], shadowColor: '#2a062f', shadowOpacity: .55, shadowRadius: 5 },
  posterStickerSide: { width: 47, height: 47, borderRadius: 24, borderWidth: 3, marginTop: 4 },
  posterIcon: { fontSize: 35 }, posterIconSide: { fontSize: 25 },
  posterMonsters: { flexDirection: 'row', height: 96, marginTop: -5, zIndex: 2 },
  posterMonstersSide: { height: 66, marginTop: -3 },
  posterRibbon: { marginTop: 'auto', width: '100%', backgroundColor: '#ffc024', borderTopWidth: 4, borderColor: '#2b082f', paddingVertical: 10 },
  posterRibbonText: { color: '#2b0a31', fontFamily: display, fontSize: 10, letterSpacing: .5, textAlign: 'center', textTransform: 'uppercase' },
  selectedPosterPill: { position: 'absolute', bottom: -15, backgroundColor: '#2b083d', borderColor: C.orange, borderWidth: 3, paddingHorizontal: 17, paddingVertical: 6, borderRadius: 18 },
  selectedPosterText: { color: C.yellow, fontFamily: display, fontSize: 11, letterSpacing: 1.1 },
  carouselDots: { flexDirection: 'row', gap: 7, marginTop: -15 },
  carouselDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: '#754183' },
  carouselDotActive: { width: 22, backgroundColor: C.orange },

  roundPill: { color: '#ff78d5', fontFamily: display, fontSize: 13, letterSpacing: .9, backgroundColor: '#39104f', borderWidth: 2, borderColor: '#9d39ad', borderRadius: 16, paddingHorizontal: 19, paddingVertical: 6 },
  memeIcon: { width: 245, height: 206, alignItems: 'center', justifyContent: 'flex-end' },
  photoCard: { width: 160, height: 136, borderRadius: 14, backgroundColor: '#72d0ef', borderWidth: 8, borderColor: C.cream, transform: [{ rotate: '5deg' }], overflow: 'hidden', shadowColor: '#15021c', shadowOpacity: .65, shadowRadius: 7 },
  sun: { position: 'absolute', width: 28, height: 28, borderRadius: 14, backgroundColor: C.yellow, right: 14, top: 14 },
  mountainA: { position: 'absolute', width: 104, height: 104, backgroundColor: '#1c785d', transform: [{ rotate: '45deg' }], bottom: -63, left: 2 },
  mountainB: { position: 'absolute', width: 94, height: 94, backgroundColor: '#24518e', transform: [{ rotate: '45deg' }], bottom: -57, right: -2 },
  photoShine: { position: 'absolute', width: 18, height: 180, top: -25, left: 28, backgroundColor: 'rgba(255,255,255,.22)', transform: [{ rotate: '24deg' }] },
  bubble: { position: 'absolute', top: 1, left: 3, width: 153, height: 82, borderRadius: 17, backgroundColor: C.cream, borderWidth: 6, borderColor: '#321042', alignItems: 'center', justifyContent: 'center', shadowColor: '#16021d', shadowOpacity: .55, shadowRadius: 6 },
  bubbleDots: { color: '#39124c', fontFamily: display, fontSize: 32, letterSpacing: 8 },
  bubbleTail: { position: 'absolute', bottom: -14, right: 24, width: 22, height: 22, backgroundColor: C.cream, borderRightWidth: 5, borderBottomWidth: 5, borderColor: '#321042', transform: [{ rotate: '45deg' }] },
  tagPill: { backgroundColor: 'rgba(42,7,57,.78)', borderRadius: 18, borderWidth: 2, borderColor: '#6f2581', paddingHorizontal: 18, paddingVertical: 7 },
  roundTag: { color: '#ff77d8', fontFamily: display, fontSize: 16, letterSpacing: 1.2 },
  roundMonsters: { flexDirection: 'row', width: '100%', justifyContent: 'space-around', marginTop: -23 },

  winnerLabel: { color: '#ff72d4', fontFamily: display, fontSize: 15, letterSpacing: 1.6, backgroundColor: 'rgba(42,6,58,.58)', borderRadius: 13, paddingHorizontal: 14, paddingVertical: 4 },
  winnerName: { fontSize: 45, lineHeight: 47, letterSpacing: 1.8 },
  crownBadge: { width: 56, height: 50, borderRadius: 25, backgroundColor: 'rgba(47,8,58,.55)', alignItems: 'center', justifyContent: 'center', marginBottom: -28, zIndex: 4 },
  crown: { color: C.yellow, fontFamily: display, fontSize: 45, lineHeight: 47 },
  pointsPanel: { width: '100%', height: 96, borderRadius: 18, backgroundColor: '#2b0841', borderWidth: 4, borderColor: '#9f32b3', flexDirection: 'row', alignItems: 'baseline', justifyContent: 'center', shadowColor: '#b735ca', shadowOpacity: .45, shadowRadius: 9 },
  pointsNumber: { color: C.orange, fontFamily: display, fontSize: 56, letterSpacing: 1 },
  pointsLabel: { color: C.yellow, fontFamily: display, fontSize: 22, marginLeft: 8 },
  votesLabel: { color: '#cf91dc', fontFamily: display, fontSize: 11, letterSpacing: 1.4 },
  voteLine: { width: '100%', height: 72, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: '#210432', borderRadius: 16, borderWidth: 3, borderColor: '#692180', paddingVertical: 5 },

  roundSub: { color: '#ff6fd2', fontFamily: display, fontSize: 14, letterSpacing: 1.2 },
  scoreList: { width: '100%', gap: 8 },
  scoreRow: { width: '100%', height: 67, backgroundColor: '#250538', borderWidth: 3, borderColor: '#672080', borderRadius: 14, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 9 },
  scoreWinner: { borderColor: C.orange, backgroundColor: '#32103f', shadowColor: C.orange, shadowOpacity: .85, shadowRadius: 10 },
  rank: { width: 34, color: C.cream, fontFamily: display, fontSize: 28, textAlign: 'center' },
  scoreAvatar: { width: 57, height: 57, borderRadius: 12, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(79,22,92,.35)' },
  scoreName: { color: C.cream, fontFamily: display, fontSize: 17, flex: 1, marginLeft: 8, letterSpacing: .5 },
  scoreValue: { color: C.yellow, fontFamily: display, fontSize: 21, letterSpacing: .5 },

  progressBody: { width: '100%', flex: 1, flexDirection: 'row', justifyContent: 'center', alignItems: 'center' },
  progressPath: { width: 94, height: 470, alignItems: 'center', justifyContent: 'space-between' },
  pathLine: { position: 'absolute', width: 10, height: 421, top: 24, backgroundColor: '#632773', borderRadius: 6, borderWidth: 2, borderColor: '#7c328c' },
  pathNode: { width: 61, height: 61, borderRadius: 31, backgroundColor: '#3b124f', borderWidth: 4, borderColor: '#9140a1', alignItems: 'center', justifyContent: 'center', zIndex: 2 },
  pathDone: { backgroundColor: '#3b971a', borderColor: '#a6ff5d' },
  pathCurrent: { backgroundColor: '#ff7215', borderColor: C.yellow, shadowColor: C.orange, shadowOpacity: 1, shadowRadius: 13 },
  pathNumber: { color: C.cream, fontFamily: display, fontSize: 29 },
  progressInfo: { width: 244, height: 470, justifyContent: 'space-around', alignItems: 'center' },
  doneCard: { position: 'absolute', top: 5, left: 0, width: 180, height: 72, borderRadius: 31, backgroundColor: '#215e12', borderWidth: 4, borderColor: '#8df249', justifyContent: 'center', paddingLeft: 25 },
  doneLabel: { color: '#a8fa7d', fontFamily: display, fontSize: 9, letterSpacing: 1.1 },
  doneGame: { color: '#78ed45', fontFamily: display, fontSize: 16, letterSpacing: .5 },
  progressDozy: { position: 'absolute', top: 67, right: -5 },
  spinNext: { position: 'absolute', top: 112, left: 0, width: 158, height: 68, borderRadius: 32, backgroundColor: '#701360', borderWidth: 4, borderColor: C.orange, justifyContent: 'center', alignItems: 'center', shadowColor: C.orange, shadowOpacity: .48, shadowRadius: 8 },
  spinNextSmall: { color: '#ff9bcf', fontFamily: display, fontSize: 8, letterSpacing: 1.1 },
  spinNextText: { color: C.cream, fontFamily: display, fontSize: 18 },
  lockCard: { position: 'absolute', right: 0, top: 202, width: 108, height: 165, borderRadius: 16, backgroundColor: '#061a3a', borderWidth: 4, borderColor: C.cyan, justifyContent: 'center', alignItems: 'center', shadowColor: C.cyan, shadowOpacity: .35, shadowRadius: 8 },
  lockIcon: { color: C.yellow, fontFamily: display, fontSize: 22 },
  lockText: { color: C.cyan, fontFamily: display, textAlign: 'center', fontSize: 16, lineHeight: 20, letterSpacing: .4 },
  bolt: { color: C.yellow, fontFamily: display, fontSize: 28 },
  progressPeepers: { position: 'absolute', right: 65, bottom: 1 },

  podiumScene: { width: '100%', height: 395, flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'center', marginTop: -8 },
  podiumEntry: { width: '33.333%', alignItems: 'center' }, podiumSecond: { marginBottom: 0 }, podiumFirst: { marginBottom: 0, zIndex: 2 }, podiumThird: { marginBottom: 0 },
  silverBlock: { width: '100%', height: 152, backgroundColor: '#3a3b68', borderWidth: 4, borderColor: '#666891', alignItems: 'center', paddingTop: 7 },
  goldBlock: { width: '100%', height: 206, backgroundColor: '#ae4f0c', borderWidth: 4, borderColor: C.orange, alignItems: 'center', paddingTop: 7, shadowColor: C.orange, shadowOpacity: .5, shadowRadius: 8 },
  bronzeBlock: { width: '100%', height: 132, backgroundColor: '#5d2230', borderWidth: 4, borderColor: '#9e4050', alignItems: 'center', paddingTop: 7 },
  podiumRank: { color: C.cream, fontFamily: display, fontSize: 30 },
  podiumPerson: { color: C.cream, fontFamily: display, fontSize: 11, letterSpacing: .3 },
  podiumScoreBlue: { color: C.cyan, fontFamily: display, fontSize: 22, marginTop: 6 },
  podiumScoreGold: { color: C.yellow, fontFamily: display, fontSize: 27, marginTop: 6 },
  podiumScorePink: { color: '#ff647d', fontFamily: display, fontSize: 22, marginTop: 6 },
});
